//GLOBAL VARIABLES HERE

//ON CLICK WITH EVENT LISTENER FOR CLICKING START
//INTIALIZE TIMER, CHANGE TO QUESTIONS

//ON CLICK EVENT LISTENER FOR ANSWER, THIS WILL GO TO NEXT SCREEN
//MAYBE INCLUDE A WHILE LOOP

//TIMER FUNCTION
//START AT 60 SECONDS
//TAKE AWAY 15 SECONDS FOR EACH WRONG ANSWER
//ELSE NOTHING

//ONCE QUESTION FUNCTION IS OVER
//DISPLAY USER INPUT SCREEN
//GATHER USERS INITIALS / NAME
//USER HITS SUBMIT
//THEN LOG TO LEADERBOARD
//DISPLAY LEADERBOARD

//QUESTION FUNCTION
//WHEN USER CLICKS START BUTTON DISPLAY FIRST QUESTION
    //IF USER SELECTS RIGHT ANSWER DISPLAY MESSAGE
    //IF USER SELECTS WRONG ANSWER DISPLAY MESSAGE
        //TAKE 15 SECONDS FROM TIMER
//REPEAT THIS FOR ALL FIVE QUESTIONS
//END FUNCTION
